update branding
watson-developer-cloud/customer-engagement-bot pull request #7
Opened 2018-03-16 15:34 UTC by ttlew

2018-03-16 18:07 UTC, germanattanasio requested changes

2018-03-16 18:07 UTC, germanattanasio commented on .env.example
> +WATSON_ASSISTANT_USERNAME=<username>
`ASSISTANT_USERNAME` not `WATSON_ASSISTANT_USERNAME`

2018-03-16 18:07 UTC, germanattanasio commented on README.md
> +1. In the JSON output, find the values for the `password` and `username` keys. Paste these values (not including the quotation marks) into the `WATSON_ASSISTANT_PASSWORD` and `WATSON_ASSISTANT_USERNA
`ASSISTANT_USERNAME`

2018-03-16 18:07 UTC, germanattanasio commented on manifest.yml
> -  conversation-prod:
This should match the README

```
     - watson-assistant-ce-tone
     - tone-analyzer-ce-tone
```

2018-03-19 17:28 UTC, ttlew commented on README.md
> +1. In the JSON output, find the values for the `password` and `username` keys. Paste these values (not including the quotation marks) into the `WATSON_ASSISTANT_PASSWORD` and `WATSON_ASSISTANT_USERNA
updated

2018-03-19 17:28 UTC, ttlew commented on manifest.yml
> -  conversation-prod:
updated

2018-04-10 13:14 UTC, germanattanasio approved these changes

2018-04-10 13:15 UTC, merged